#!/bin/bash

# 创建一个新的 tmux 会话
tmux new-session -d -s my_servers

# 创建一个新的窗口
tmux new-window -t my_servers:1

# 将当前窗口分割为四个面板
tmux split-window -h -t my_servers:1
tmux split-window -v -t my_servers:1
tmux select-pane -t 0
tmux split-window -v -t my_servers:1

# 在每个面板中运行一个 SSH 命令来连接到服务器
tmux send-keys -t my_servers:1.0 'ssh hw' Enter
tmux send-keys -t my_servers:1.1 'ssh weykon2' Enter
tmux send-keys -t my_servers:1.2 'ssh usa' Enter
tmux send-keys -t my_servers:1.3 'ssh hz' Enter

# 附加到 tmux 会话
tmux attach -t my_servers
